// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dto "github.com/rheadavin/hr-go-api/internal/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/rheadavin/hr-go-api/internal/models"
)

// DivisionServiceInterface is an autogenerated mock type for the DivisionServiceInterface type
type DivisionServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *DivisionServiceInterface) Create(req dto.CreateDivisionRequest) (*dto.DivisionResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.DivisionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateDivisionRequest) (*dto.DivisionResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateDivisionRequest) *dto.DivisionResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DivisionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.CreateDivisionRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *DivisionServiceInterface) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: page, limit, search
func (_m *DivisionServiceInterface) FindAll(page int, limit int, search string) ([]dto.DivisionResponse, int64, error) {
	ret := _m.Called(page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []dto.DivisionResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]dto.DivisionResponse, int64, error)); ok {
		return rf(page, limit, search)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []dto.DivisionResponse); ok {
		r0 = rf(page, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.DivisionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) int64); ok {
		r1 = rf(page, limit, search)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(page, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: id
func (_m *DivisionServiceInterface) FindByID(id uint) (*models.Division, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Division, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Division); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, req
func (_m *DivisionServiceInterface) Update(id uint, req dto.UpdateDivisionRequest) (*dto.DivisionResponse, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *dto.DivisionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, dto.UpdateDivisionRequest) (*dto.DivisionResponse, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(uint, dto.UpdateDivisionRequest) *dto.DivisionResponse); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DivisionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, dto.UpdateDivisionRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDivisionServiceInterface creates a new instance of DivisionServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDivisionServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DivisionServiceInterface {
	mock := &DivisionServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
